language: node_js
node_js: lts/*
services:
  - postgresql
env:
  global:
    - CC_TEST_REPORTER_ID=38dbcc770fbe1eaba4bea068ac28dfee0ea44c4faf87cc1dd9fbba3ee6381a2e
    - DATABASE_URL=postgres://postgres@localhost:5432/wayfarer_db
    - JWT_SECRET=ac9ca94cay9a3cnac3llo4ob49895cglbwlooqboavai3ab39b3a
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -U postgres -c 'create database wayfarer_db;'
  - psql -U postgres -d wayfarer_db -a -f ./schema.sql
script:
  - npm run build
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
